/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Servidor */

#ifndef _Included_S
#define _Included_S
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Servidor
 * Method:    callTorch
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_S_callTorch
  (JNIEnv *, jobject, jintArray);

JNIEXPORT void JNICALL Java_S_startTorch
  (JNIEnv * env, jobject);
#ifdef __cplusplus
}
#endif
#endif
