/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Servidor */

#ifndef _Included_Servidor
#define _Included_Servidor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Servidor
 * Method:    callTorch
 * Signature: ([B)[I
 */
//JNIEXPORT jintArray JNICALL Java_Servidor_callTorch  (JNIEnv *, jobject, jintArray);

JNIEXPORT jint JNICALL Java_Servidor_callTorch  (JNIEnv *, jobject, jint opc);
JNIEXPORT void JNICALL Java_Servidor_reporte    (JNIEnv * env, jobject);
JNIEXPORT void JNICALL Java_Servidor_startTorch
  (JNIEnv * env, jobject, jint opc);
#ifdef __cplusplus
}
#endif
#endif
